service: alexa-skill-debug

custom:
  stage: ${opt:stage, self:provider.stage}
  alexa_skill_id:
    production: amzn1.ask.skill.53cfd959-17c1-40f5-84ea-190aca778693
    staging: amzn1.ask.skill.a97e9076-86e4-4af1-97ef-c90606c570f3
  api_url:
    production: https://api.echohub.io
    staging: https://api.staging.echohub.io

provider:
  name: aws
  runtime: nodejs6.10
  profile: echohub
  stage: staging
  region: us-east-1
  memorySize: 128
  cfLogs: true
  versionFunctions: false
  environment:
    ALEXA_SKILL_ID: ${self:custom.alexa_skill_id.${self:custom.stage}}
    ECHOHUB_API_URL: ${self:custom.api_url.${self:custom.stage}}

package:
  individually: true

functions:
  handler:
    handler: src/handler.default
    events:
      - alexaSkill

plugins:
  - serverless-webpack
    #  - serverless-sentry
